// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE8FXbcsjCdj20xbH302mUfaaLXWkrl98',
    appId: '1:170793135287:web:874fdd15cdecccc20e3132',
    messagingSenderId: '170793135287',
    projectId: 'studentdirectory-15959',
    authDomain: 'studentdirectory-15959.firebaseapp.com',
    storageBucket: 'studentdirectory-15959.firebasestorage.app',
    measurementId: 'G-2JSKSS6LHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArR5YKefcbdv5qO6QX3O8UxxkSBZQBumA',
    appId: '1:170793135287:android:bd7fb1a170efac8e0e3132',
    messagingSenderId: '170793135287',
    projectId: 'studentdirectory-15959',
    storageBucket: 'studentdirectory-15959.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr5STPiE5Nswb_cFAV2LwnAjurO5_3RuM',
    appId: '1:170793135287:ios:a07d0064124c717c0e3132',
    messagingSenderId: '170793135287',
    projectId: 'studentdirectory-15959',
    storageBucket: 'studentdirectory-15959.firebasestorage.app',
    iosBundleId: 'com.example.studentdirectoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr5STPiE5Nswb_cFAV2LwnAjurO5_3RuM',
    appId: '1:170793135287:ios:a07d0064124c717c0e3132',
    messagingSenderId: '170793135287',
    projectId: 'studentdirectory-15959',
    storageBucket: 'studentdirectory-15959.firebasestorage.app',
    iosBundleId: 'com.example.studentdirectoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE8FXbcsjCdj20xbH302mUfaaLXWkrl98',
    appId: '1:170793135287:web:ef0e837a973646550e3132',
    messagingSenderId: '170793135287',
    projectId: 'studentdirectory-15959',
    authDomain: 'studentdirectory-15959.firebaseapp.com',
    storageBucket: 'studentdirectory-15959.firebasestorage.app',
    measurementId: 'G-QP4FDFDRK2',
  );
}
